### ISSUE TITLE
Broken link to battery API project

### ISSUE THREAD

**Issue by alexmorley** [r3bl/r3bl.github.io#4]
Just FYI :)

**Comment by aleksandar-todorovic** [comment]
Well, on the positive side, it's live again, on the same location.

On the negative side, Battery Status API was just a W3C suggestion, and nothing specifically changed in that API since 2014.

Still works on Chromium-based browsers, but it's been removed from Firefox (both desktop and Android) and it's only a matter of time before it gets removed from Chromium-based browsers as well.

Thanks for letting me know! :smile:
